# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' @title Generate a bullet chart for in country indicator gap analysis
#' @description This chart is designed to allow for quick gap analysis based on 
#'   all outcome indicators within the same country
#'
#' @param data RBM QA dataset - expect a few pre-defined variables to works well..
#' @param thisoperation_mco which operation plan to chart
#'
#' @importFrom unhcrthemes theme_unhcr
#'
#' @return list with a plot
#' 
#' @export
#'
#' @examples
#' data <- prepare_qa_data(activityInfoTable= "cdn6y40lm87wi522")
#' incountry_gap(data, thisoperation_mco = "Brazil ABC" )
incountry_gap <- function(data, thisoperation_mco){
    library(tidyverse)
  
  # thiscountry <-  "ECU"
  #names(data)
  thisdata1 <- data |>
      dplyr::filter(operation_mco == thisoperation_mco) |>
      dplyr::mutate(country = stringr::str_replace(country,
                                                   " \\(Bolivarian Republic of\\)", "")) |>
      dplyr::distinct() |>
      dplyr::mutate(means_verification_data_source = stringr::str_replace_all(means_verification_data_source,
                                                                      "https://", " " ) ) |>
      dplyr::rename(target = target_2023, 
                    baseline = baseline_2023_percent, 
                    actual = actual_2023) |>
      
      dplyr::mutate(  actual = as.numeric(actual),
                      target = as.numeric(target),
                      gap_actual_target = - round( (  target - actual) /  target *100  ,2 ),
                      gap_color = dplyr::case_when(
                        gap_actual_target >= 0     ~ "green",
                        gap_actual_target < 0  & gap_actual_target >= -10    ~ "orange",
                        gap_actual_target < -10     ~ "red",  
                                                   TRUE ~ ""),
                      gap_actual_green = - round( ( threshold_green - actual) /  threshold_green *100 ,2 ) )     |>  
      dplyr::mutate(means_verification_data_source = substr(means_verification_data_source, 0 , 50)) |>
      tidyr::unite(col =  "data_info", 
                   all_of( c("means_verification_data_source", "means_verification_additional_data_sources") ), 
                   na.rm = TRUE, 
                   sep = "<br> ",
                   remove = FALSE) |>
      ## Trying to sanitize to get rid of..
      ## Error: gridtext has encountered a tag that isn't supported yet: <a>
      # Only a very limited number of tags are currently supported.
      
      dplyr::mutate(data_info = stringr::str_replace_all(data_info, "https://", " " ) ) |>
      dplyr::mutate(data_info = stringr::str_replace_all(data_info, "www.", " " ) ) |>
      
      dplyr::mutate( group = as.character(glue::glue("{country}/{means_verification_population_type}") ) ) |>
      dplyr::mutate( operation = as.character(glue::glue("{means_verification_outcome_area} - {means_verification_indicator} / {means_verification_population_type}") ) ) |>
      #dplyr::arrange(desc(actual))
      dplyr::group_by(means_verification_indicator) |>
      dplyr::arrange(desc( actual), .by_group=TRUE ) |> 
      dplyr::ungroup(means_verification_indicator) 

## We keep only when there's value for plotting!
thisdataOutcome <- thisdata1   |>
  dplyr::filter( !(is.na(actual))) |>
  dplyr::select(#key, keyctr1, 
                means_verification_results_level, 
                means_verification_indicator, 
                means_verification_outcome_area,  
                means_verification_population_type, 
                actual, 
                target, 
                gap_actual_target,
                gap_color,
                threshold_green, 
                gap_actual_green,
                baseline, 
                standard_direction,
                Reverse, 
                QA_logical, 
                operation_mco,   country,  
                group, operation) |>
  dplyr::filter (! is.na(gap_actual_target)) |>
  dplyr::filter (! is.nan(gap_actual_target)) |>
  dplyr::filter (means_verification_results_level == "Outcome")    

 country <- thisdataOutcome |>
  dplyr::distinct(country) |>
  dplyr::pull()
  ## case there's no data at all
  if( nrow(thisdataOutcome) == 0) {
    info <-  paste0("No gap analysis could be \n produced for \n outcome indicator values \n in ", thiscountry)
    p <- ggplot() +  annotate("text",  x = 1, y = 1, size = 12,
                              label = info ) +  theme_void()
  
  } else if(nrow(thisdataOutcome)> 0) {
  
  ## and now the plot
  p <-  ggplot2::ggplot(  data = thisdataOutcome) +
        ggplot2::coord_flip()  +
    # geom_errorbar(  aes(x = reorder(operation, - gap_actual_target), 
    #                       ymin = gap_actual_green, 
    #                       ymax = gap_actual_green),
    #                   color = "black", 
    #                   #width = 0.45, 
    #                   linewidth = 1)   +
    ggplot2::geom_col(   ggplot2::aes(x = reorder(operation, - gap_actual_target), 
                    y = gap_actual_green  ),
                fill = "grey50",    
                alpha = 0.3,    
                width = 0.9,
                color = NA ) + 
    ggplot2::geom_col(   ggplot2::aes(x = reorder(operation, - gap_actual_target), 
                    y = gap_actual_target,
                    fill = gap_color ),
                #fill = "#0072BC",    
                width = 0.7,
                color = NA ) + 
    ggplot2::scale_fill_manual(values = c( "red" = "#D3212C",    "orange" = "#FF980E",  "green" = "#069C56")) +
    ggplot2::geom_text( ggplot2::aes(x = reorder(operation, - gap_actual_target), 
                   y = gap_actual_target,
                   label = paste(round(gap_actual_target, 1), " %") ),
               #hjust = 1.5, 
               size = 2.5,
               color = "black")  +
    # scale_y_continuous( label = scales::label_percent(accuracy = 0,
    #                                    suffix = "%") ) +
    ggplot2::scale_y_continuous( label =  scales::label_number(accuracy = 1, 
                                                      scale_cut = scales::cut_short_scale(),
                                                      suffix = "%") )+
    ggplot2::scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 70)) +
  
    unhcrthemes::theme_unhcr(font_size = 11, 
                             #rel_small = 6/9,
                             grid = "X", 
                             axis = "y") +
    ggplot2::theme(  #axis.text.y = ggtext::element_markdown(),
            legend.position = "none")+
    ggplot2::labs( x = "", y = "" ,
          title = stringr::str_wrap( 
            paste0("Outcome RBM Indicators  | 2023 ",country  ) ,  100),
          subtitle = stringr::str_wrap( paste0( 
            "Comparing Gap between Actual value and Target (colored) / Acceptable Threshold (grey)" ) ,
            110),
          caption = stringr::str_wrap( "Source: UNHCR RBM / Compass.  Calculation is performed to measure and compare gap between actual value and target value [(target-actual)/target], as well as value and acceptable threshold  - when relevant - [(threshold_green-actual)/threshold_green]" ,
          110) )  
   }
  out <- list(  plot = p)
  return(out)
}
