# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' @title Generate a bullet chart for in country indicator gap analysis
#' @description This chart is designed to allow for quick gap analysis based on 
#'   all outcome indicators within the same country
#'
#' @param data RBM QA dataset - expect a few pre-defined variables to works well..
#' 
#' @param budget table  from results.unhcr.org 4.6.1_Budget_Download.xlsx 
#' 
#' @param thisoperation_mco which operation plan to chart
#'
#' @importFrom unhcrthemes theme_unhcr
#'
#' @return list with a plot
#' 
#' @export
#'
#' @examples
#' data <- prepare_qa_data(activityInfoTable= "cdn6y40lm87wi522")
#' budget <- readxl::read_excel( system.file("4.6.1_Budget_Download.xlsx", package = "ProgQA"),  skip = 1)|>  
#' #budget <- readxl::read_excel( here::here("data-raw", "4.6.1_Budget_Download.xlsx"),  skip = 1)|>
#'   janitor::clean_names() 
#' incountry_gap(data,budget, thisoperation_mco = "Brazil ABC" )
#'
#' incountry_gap(data,budget, thisoperation_mco = "Colombia ABC" )
#'
#' incountry_gap(data,budget, thisoperation_mco = "Mexico ABC" )
incountry_gap <- function(data, budget, thisoperation_mco){
    library(tidyverse)
  
  # thiscountry <-  "ECU"
  #names(data)
  thisdata1 <- data |>
      dplyr::filter(operation_mco == thisoperation_mco) |>
      dplyr::mutate(country = stringr::str_replace(country,
                                                   " \\(Bolivarian Republic of\\)", "")) |>
      dplyr::distinct() |>
      dplyr::rename(target = target_2023, 
                    baseline = baseline_2023, 
                    actual = actual_2023) |>
      dplyr::mutate(  actual = as.numeric(actual),
                      target = as.numeric(target),
                      ## Calculating gap to standard
                      gap_green =  round( (  actual - threshold_green ) / 
                                           dplyr::if_else(threshold_green == 0, 1, threshold_green) * 
                                           dplyr::if_else(threshold_green == 0, 1, 100)  ,2 ),
                      gap_green = dplyr::if_else(Reverse == TRUE, 
                                                         gap_green * -1, 
                                                         gap_green),  
                      gap_color = dplyr::case_when(
                        gap_green >= 0     ~ "green",
                        gap_green < 0  & gap_green >= -15    ~ "orange",
                        gap_green < -15     ~ "red",  
                                                   TRUE ~ "") ,
                      ## Calculating deviation to target        
                      deviation_actual_target =  round( ( actual - target ) / 
                                                           dplyr::if_else(target == 0, 1, target) * 
                                                           dplyr::if_else(target == 0, 1, 100) ,2 ),
               
                      ## Account for indicator direction
                      deviation_actual_target = dplyr::if_else(Reverse == TRUE, 
                                                         deviation_actual_target * -1, 
                                                         deviation_actual_target) )     |>  
      dplyr::mutate( indd = as.character(glue::glue("{means_verification_indicator} / {means_verification_population_type}") ) ) 

## We keep only when there's value for plotting!
thisdataOutcome <- thisdata1   |>
  dplyr::filter( !(is.na(actual))) |>
  dplyr::select(#key, keyctr1, 
                means_verification_results_level, 
                means_verification_indicator, 
                means_verification_outcome_area,  
                means_verification_population_type, 
                indd,
                actual, 
                target, 
                gap_green,
                gap_color,
                threshold_green, 
                deviation_actual_target,
                baseline, 
                standard_direction,
                Reverse, 
                operation_mco,   country) |>
  dplyr::filter (! is.na(gap_green)) |>
  dplyr::filter (! is.nan(gap_green)) |>
  dplyr::filter (means_verification_results_level == "Outcome")    


## merge data on indicators and the one on budget
budget_outcome <- budget |> 
  dplyr::filter(operation == thisoperation_mco) |>
  dplyr::filter(scenario == "Detailed WOL") |>
  dplyr::group_by(operation_code, operation,  outcome_area) |>
  dplyr::summarise(cost_usd = sum(cost_usd, na.am = TRUE)) |>
  dplyr::group_by(operation_code, operation) |>
  dplyr::mutate( sector_pct = round( cost_usd / sum(cost_usd, na.am = TRUE) * 100, 2) )

thisdataOutcome2 <- thisdataOutcome |>
  dplyr::left_join(budget_outcome, by = c("means_verification_outcome_area"="outcome_area")) |>
  dplyr::mutate(sector_pct = dplyr::if_else(is.na(sector_pct), 0, sector_pct),
                explain = glue::glue("<span style='font-size:12pt'><b>Actual value: {round(actual,2)} </b></span><span style='font-size:8pt'><br> <i> {sector_pct} % of Resource Spent on {means_verification_outcome_area}</i></span>"),
                pos = gap_green >= 0) 

 country <- thisdataOutcome |>
  dplyr::distinct(country) |>
  dplyr::pull()
  ## case there's no data at all
  if( nrow(thisdataOutcome) == 0) {
    info <-  paste0("No gap analysis could be \n produced for \n outcome indicator values \n in ", thiscountry)
    p <- ggplot() +  annotate("text",  x = 1, y = 1, size = 12,
                              label = info ) +  theme_void()
  
  } else if(nrow(thisdataOutcome)> 0) {
  
  ## and now the plot
  p <-   ggplot2::ggplot(  data = thisdataOutcome2) +
  ggplot2::coord_flip()  +
  ggplot2::geom_col(   ggplot2::aes(x = reorder(indd, - gap_green), 
                                  y = gap_green,
                                  fill = pos), 
                    # fill = "#FFBD31", 
                     alpha = .5,
                     width = 0.7,
                     color = NA ) + 
    ggplot2::scale_fill_manual(values = c( "TRUE" = "#0072BC",    "FALSE" = "#FFBD31" )) +
    ## Position label differently in the bar in white - outside bar in black
    ggtext::geom_richtext( ggplot2::aes(x = reorder(indd, - gap_green), 
                                        y = gap_green,
                                        label = explain ),
                           fill = NA, label.color = NA, # remove background and outline
                           label.padding = grid::unit(rep(0, 4), "pt") , # remove padding
      data = subset( thisdataOutcome2, gap_green < abs(max(gap_green) / 2.5) ),
      hjust = -0.1 ,  vjust = 0.5, colour = "black", size = 3    ) +
    ## Position label differently in the bar in white - outside bar in black
    ggtext::geom_richtext( ggplot2::aes(x = reorder(indd, - gap_green), 
                                        y = gap_green,
                                        label = explain ),
                           fill = NA, label.color = NA, # remove background and outline
                           label.padding = grid::unit(rep(0, 4), "pt") , # remove padding
      data = subset(thisdataOutcome2, gap_green >= abs(max(gap_green) / 2.5) ),
      hjust = 1.1 , vjust = 0.5, colour = "black",  size = 3)  +
     
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, .2)),
                              label =  scales::label_number(accuracy = 1, 
                                                             scale_cut = scales::cut_short_scale(),
                                                             suffix = "%") )+
  ggplot2::scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 70)) +
  
  unhcrthemes::theme_unhcr(font_size = 11, 
                           #rel_small = 6/9,
                           grid = "X", 
                           axis = "y") +
  ggplot2::theme(  #axis.text.y = ggtext::element_markdown(),
    legend.position = "none")+
  ggplot2::labs( x = "", 
                 y = "Relative distance in % between actual value and specific acceptable threshold for each indicator - the broader is the gap, the more negative the distance..." ,
                 title = stringr::str_wrap( 
                   paste0("Results Vs Resources Allocation | 2023 ",country  ) ,  100),
                 subtitle = stringr::str_wrap( paste0( 
                   "Comparing Gap between Actual value and Standard Acceptable Threshold" ) ,
                   110),
                 caption = stringr::str_wrap( "Source: UNHCR RBM / Compass (provisional)" ,
                                              110) ) 
   }
  out <- list(  plot = p)
  return(out)
}
