# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' summary_qa_table
#' 
#' A summary table of main QA issues
#' @param data table resulting from  prepare_qa_data()
#' 
#' @import flextable
#' 
#' @return
#' 
#' @export
#' @examples
#' data <- prepare_qa_data(activityInfoTable= "cdn6y40lm87wi522")
#' summary_qa_table(data)
summary_qa_table <- function(data){
  
  ## other summary as per DPSR
summary <- rbind(   
#% of 2023 actuals available
#Comp2_1 = dplyr::if_else( is.na(actual_2023), "Missing Actual", NA ),  
  round(prop.table(table( data$operation_mco, data$Comp2_1, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
# % of baselines available
#Comp2_2 = dplyr::if_else( is.na(baseline_2023_percent), "Missing Baseline", NA ),
              round(prop.table(table( data$operation_mco, data$Comp2_2, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
#% of targets available
#Comp2_3 = dplyr::if_else( is.na(target_2023) & means_verification_results_level == "Outcome", "Missing Target", NA ) ) |>
              round(prop.table(table( data$operation_mco, data$Comp2_3, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2)))  )  |>
          dplyr::mutate(Assess = dplyr::case_when(
             Var2 == "Missing Actual" ~ "% of 2023 actuals available",
             Var2 == "Missing Baseline" ~ "% of baselines available",
             Var2 == "Missing Target" ~ "% of targets available",
              TRUE ~ "" ) ) |>
  dplyr::mutate(Value = round(100 - Freq,1)  ) |>
  dplyr::rename(Plan = Var1 ) |>
  dplyr::select( Plan, Assess, Value) |>
  tidyr::pivot_wider(names_from = Assess, values_from = Value) |>
  dplyr::select("Plan",
                "% of baselines available",
                "% of targets available",	
                "% of 2023 actuals available" ) 
library(tidyverse)
summary2 <- summary |>
  dplyr::ungroup()   |>
 # add_row(year = 'mean', !!! colMeans(.[-1]))  
  dplyr::reframe(Plan = c(as.character(Plan), 'Regional Average'),
            across(where(is.numeric), ~ c(., mean(.)))) |>           
  # Using dplyr functions
  dplyr::mutate_if(is.numeric,
            round,
            digits = 1)
  

ft_2 <- flextable::flextable( summary2 )
ft_2 <- flextable::bg(ft_2, bg = "grey95", part = "header")
ft_2  <- flextable::width(ft_2 , width = 1)
colourer <- scales::col_numeric( palette = "RdYlBu", domain = c(0, 100) )
ft_2 <- flextable::bg(ft_2, j = c(2:4),    bg = colourer, part = "body"  )

## return the results
return(ft_2) 
 
    
}
