# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' summary_qa_chart
#' 
#' Display a summary QA charts based on data
#' @param data table resulting from  prepare_qa_data()
#' 
#' @return ggplot2 chart
#' 
#' @import ggplot2
#' @importFrom unhcrthemes theme_unhcr
#' 
#' @export
#' @examples
#' data <- prepare_qa_data(activityInfoTable= "cdn6y40lm87wi522")
#' summary_qa_chart(data)
summary_qa_chart <- function(data ){
  
  
  
    summary1  <- rbind( 
              round(prop.table(table( data$operation_mco, data$Comp1_1, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              # round(prop.table(table( data$operation_mco, data$Comp1_2, useNA = "ifany"), margin=1)* 100 , 1) |> 
              #   as.data.frame()|>
              #   dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Comp2_1, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Comp2_2, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Comp2_3, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              # round(prop.table(table( data$operation_mco, data$Comp3, useNA = "ifany"), margin=1)* 100 , 1) |> 
              #   as.data.frame()|>
              #   dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Comp4, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Acc1_1, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Acc1_2, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              # round(prop.table(table( data$operation_mco, data$Acc1_3, useNA = "ifany"), margin=1)* 100 , 1) |> 
              #   as.data.frame()|>
              #   dplyr::filter( !(is.na(Var2))),
              # round(prop.table(table( data$operation_mco, data$Acc2_1, useNA = "ifany"), margin=1)* 100 , 1) |> 
              #   as.data.frame()|>
              #   dplyr::filter( !(is.na(Var2))),
              # round(prop.table(table( data$operation_mco, data$Acc2_2, useNA = "ifany"), margin=1)* 100 , 1) |> 
              #   as.data.frame()|>
              #   dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Acc3_1, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Acc3_2, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Acc5_1, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              # round(prop.table(table( data$operation_mco, data$Acc5_2, useNA = "ifany"), margin=1)* 100 , 1) |> 
              #   as.data.frame()|>
              #   dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Acc5_3, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Acc5_4, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Cons1_1, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))),
              round(prop.table(table( data$operation_mco, data$Cons1_2, useNA = "ifany"), margin=1)* 100 , 1) |> 
                as.data.frame()|>
                dplyr::filter( !(is.na(Var2))) #,
              # round(prop.table(table( data$operation_mco, data$Cons1_3, useNA = "ifany"), margin=1)* 100 , 1) |> 
              #   as.data.frame()|>
              #   dplyr::filter( !(is.na(Var2))),
              # round(prop.table(table( data$operation_mco, data$Cons1_4, useNA = "ifany"), margin=1)* 100 , 1) |> 
              #   as.data.frame()|>
              #  dplyr::filter( !(is.na(Var2))) 
              )   |>
  dplyr::filter(Freq > 0) 

p <- summary1 |>
  ggplot2::ggplot(  ggplot2::aes(x = Var1, 
               y = Var2, 
               fill = Freq)) +
  ggplot2::geom_tile(color = "white",
            lwd = 1.5,
            linetype = 1) +
  ggplot2::coord_fixed() +
  ggplot2::geom_text( ggplot2::aes(label = Freq), color = "grey25", size = 2) + 
  ggplot2::scale_y_discrete(labels = scales::label_wrap(50)) + 
  #scale_fill_gradient2(low = "#069C56",    mid = "#FF980E",   high = "#D3212C") +
  ggplot2::scale_fill_gradientn(colors = hcl.colors(7,  palette = "viridis", alpha = 0.6, rev = TRUE)) +
  ggplot2::coord_fixed() +
  unhcrthemes::theme_unhcr(font_size = 13, 
                          # rel_small = 5/9,
                           grid = FALSE, 
                           axis = FALSE) +
  ggplot2::theme(legend.position = "none", 
        axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 0.5) ) +
  ggplot2::labs( x = "", y =  "" ,
        title = stringr::str_wrap( paste0("RBM Systematic Quality Check: % of indicator with issues") , 60),
        subtitle = stringr::str_wrap( paste0("Regional Comparison Americas | 2023 Quality Assurance" ) ,
                                      80),
        caption = "Source: UNHCR RBM / Compass (provisional)") 

return(p)

    
}
